### ISSUE TITLE
Minor bug with CountDownContainer's 'sum' function

### ISSUE THREAD

**Issue by s-munro** [story-squad/classroom-rumble#41]
The `sum` function in `CountDownContainer` counts down in terms of seconds, but is counting hours, minutes, and seconds all as the same unit (see below). 

<img width="676" alt="Screen Shot 2021-04-07 at 10 30 50 PM" src="https://user-images.githubusercontent.com/68410363/113960279-3f9bff80-97f2-11eb-8bd8-5e89f9a72450.png">

This causes the following interaction:

<img width="1790" alt="Screen Shot 2021-04-07 at 10 29 56 PM" src="https://user-images.githubusercontent.com/68410363/113960346-5cd0ce00-97f2-11eb-9aad-7294b8905aa6.png">

Regardless, it manages to not hit 0 before the allotted time is up, since every 60 seconds the 'minutes' change in timeLeft, thus changing the result of sum to reset back another 60 seconds.  This doesn't currently cause any game-breaking bugs, but I'm thinking we should probably fix this.  It seems to be as easy as doing the following:

<img width="646" alt="Screen Shot 2021-04-07 at 10 33 01 PM" src="https://user-images.githubusercontent.com/68410363/113960541-a4eff080-97f2-11eb-8f90-b227bc94f01a.png">

The fix can then be seen in the console here:

<img width="1792" alt="Screen Shot 2021-04-07 at 10 33 10 PM" src="https://user-images.githubusercontent.com/68410363/113960564-aae5d180-97f2-11eb-8c11-c29657fbbb47.png">

Thoughts?

**How to reproduce?**
- add `console.log(total)` on the sum function, and start a rumble.  The total will be logged every second, for as long as `total !== 0`

**Comment by VictorDronov** [comment]
I have nothing against changing it. It is more of what I was going for and, good catch didn't realize that it was only doing 60 seconds at a time.
